[WIP] Add automated release GitHub action

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -121,3 +121,38 @@ jobs:
         with:
           name: gcft-${{ steps.vars.outputs.full_version }}-${{ matrix.artifact }}
           path: dist/release_archive_${{ steps.vars.outputs.full_version }}_x64${{ matrix.upload_path_suffix }}
+
+  # Trigger a release like so:
+  # git tag 0.0.0
+  # git push origin 0.0.0
+  release:
+    name: Release
+    if: startsWith(github.ref, 'refs/tags/')
+    runs-on: ubuntu-latest
+    needs: [ build ]
+    permissions:
+      contents: write
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Check git tag against txt version
+        shell: bash
+        run: |
+          set -eou pipefail
+          tag='${{github.ref}}'
+          tag="${tag#refs/tags/}"
+          version=$(cat version.txt | head -1)
+          if [ "$tag" != "$version" ]; then
+            echo "::error::Git tag doesn't match the txt version! ($tag != $version)"
+            exit 1
+          fi
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: artifacts
+      - name: Release
+        uses: softprops/action-gh-release@v2
+        with:
+          files: artifacts/*
+          draft: true
+          generate_release_notes: true
